[package]
name = "avail-signer-generator"
version = "0.1.0"

edition = "2021"

[dependencies]
google-cloud-kms = "0.5.1"
google-cloud-storage = "0.22.1"
rand = "0.8.4"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }